[project]
name = "acoular-directivity-utils"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = ['acoular']

[tool.uv.sources]
acoular = { path = "packages/acoular", editable=true}
